name: arweave
description: ""
version: 3.8.3
environment:
  sdk: ">=3.0.0 <4.0.0"
publish_to: none

dependencies:
  cryptography: ^2.5.0
  http: ^1.1.0
  json_annotation: ^4.0.1
  jwk: ^0.1.0
  meta: ^1.7.0
  pointycastle: 3.7.4
  built_value: ^8.0.6
  js: ^0.6.3
  retry: ^3.1.0
  base32: ^2.1.1
  async: ^2.9.0
  mutex: ^3.0.1
  bip39: ^1.0.6
  hash: ^1.0.4
  fpdart: ^1.1.0
  better_cryptography: ^1.0.0+1
  fetch_client:
    git:
      url: https://github.com/ardriveapp/fetch_client.git
      ref: PE-4754-address-code-review-comments-on-uploader-downloader-implementations
  dio: ^5.3.3

dependency_overrides:
  fetch_api: 1.0.1
  pointycastle: 3.7.4


dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^6.1.4
  lints: ^1.0.1
  test: ^1.17.8
